added socket
Marhotskii/spp_2 pull request #2
Opened 2020-05-16 11:02 UTC by Marhotskii

2020-05-16 23:04 UTC, DmitryGolubko requested changes

2020-05-16 23:04 UTC, DmitryGolubko commented on controllers/tasksRepository.js
> +}
Предыдущую засчитал, но здесь надо поправить, разные сущности - разные модели - разные контроллеры

2020-05-17 13:01 UTC, Marhotskii commented on controllers/tasksRepository.js
> +}
А может можно эту так оставить, а следующую я бы уже переделал,? прост следующая у меня тоже сделана для разных сущностей

2020-05-17 17:52 UTC, DmitryGolubko approved these changes
Принято

2020-05-17 23:29 UTC, closed without merging